# Generated by Django 3.1.6 on 2021-02-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributes',
            options={'verbose_name': 'ویژگی محصولات'},
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='description',
            field=models.TextField(verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام ویژگی'),
        ),
    ]
