# Generated by Django 3.1.6 on 2021-02-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_product', '0009_remove_product_attributes'),
        ('TopKala_attributes', '0004_remove_productattributes_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributes',
            name='products',
            field=models.ManyToManyField(to='TopKala_product.Product'),
        ),
    ]
