# Generated by Django 3.1.6 on 2021-02-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_category', '0001_initial'),
        ('TopKala_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='TopKala_category.ProductCategory', verbose_name='دسته بندی'),
        ),
    ]
