# Generated by Django 3.1.6 on 2021-02-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_attributes', '0001_initial'),
        ('TopKala_product', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(to='TopKala_attributes.ProductAttributes', verbose_name='ویژگی های محصول'),
        ),
    ]
