# Generated by Django 3.1.6 on 2021-02-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_attributes', '0002_auto_20210224_2011'),
        ('TopKala_product', '0004_auto_20210224_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(to='TopKala_attributes.ProductAttributes', verbose_name='ویژگی های محصول'),
        ),
    ]
