# Generated by Django 3.1.6 on 2021-02-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_attributes', '0002_auto_20210224_2011'),
        ('TopKala_product', '0005_auto_20210224_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TopKala_attributes.productattributes', verbose_name='ویژگی های محصول'),
            preserve_default=False,
        ),
    ]
