# Generated by Django 3.1.6 on 2021-02-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_product', '0006_auto_20210224_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
    ]
