# Generated by Django 3.1.6 on 2021-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_attributes', '0004_remove_productattributes_products'),
        ('TopKala_product', '0007_remove_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(to='TopKala_attributes.ProductAttributes'),
        ),
    ]
