# Generated by Django 3.1.6 on 2021-02-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_product', '0008_product_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
    ]
