# Generated by Django 3.1.6 on 2021-02-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_product', '0009_remove_product_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='special_sale',
            field=models.BooleanField(default=False, verbose_name='فروش ویژه'),
        ),
    ]
