# Generated by Django 3.1.6 on 2021-02-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TopKala_product', '0010_auto_20210228_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbrand',
            options={'verbose_name': ' برند', 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='TopKala_product.productbrand', verbose_name='برند'),
            preserve_default=False,
        ),
    ]
